#! /usr/bin/env python3

import sys
import os

print(os.path.abspath(sys.argv[0]))
os.environ['PYTHONPATH'] = os.path.dirname(os.path.dirname(os.path.abspath(sys.argv[0])))
parser = argparse.ArgumentParser(description='xa simulator')
parser.add_argument('--input', '-i', metavar='input file', type=str, \
                    required=True, help='input file')
parser.add_argument('--token', '-t', metavar='token', type=str, \
                    required=True, help='token')
parser.add_argument('--output', '-o', metavar='prefix', type=str, \
                    required=True, help='prefix')
args = parser.parse_args()
xa = os.path.dirname(sys.argv[0]) + '/xa.py'
command = [xa, '-i', args.input, '-o', args.output, '-t', args.token]
process = subprocess.Popen(command)
process.wait()
sys.exit(process.returncode)
